version: "3.8"

services:
  backend:
    build: .
    container_name: summar-ease-backend
    command: gunicorn summar_ease.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env # Explicitly reference your .env file here
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=${SECRET_KEY} # Use the value from .env
      - DJANGO_DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: summar-ease-db
    environment:
      POSTGRES_DB: summar_ease_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
